### PR TITLE
Frank/#165 fix

### LINKED ISSUE #165: kv-asset-handler can translate 206 responses to 200 responses
TL;DR: I think this line should preserve whatever response status code `cache.match()` returned: https://github.com/cloudflare/kv-asset-handler/blob/3228cd78de1f4f61d74cecb13a3b19054d67d501/src/index.ts#L206

Originally reported by @willbicks here: https://github.com/cloudflare/wrangler/issues/1746

For a fuller investigation, please read: https://community.cloudflare.com/t/pdfs-downloaded-from-cfworkers-wrangler-corrupted/238857/10

@shagamemnon I think you worked on this code previously -- would you mind taking a look? Is the fix as easy as I hope it is?

### PR DESCRIPTION
**Pull request by shagamemnon**
Fixes #165 :)

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -203,7 +203,23 @@ const getAssetFromKV = async (event: FetchEvent, options?: Partial<Options>): Pr
...
-      response = new Response(response.body, { headers })
+      // fixes #165
+      let opts = {
+        headers,
+        status: 0,
+        statusText: ''
+      }
+      if (response.status) {
+        opts.status = response.status
+        opts.statusText = response.statusText
```
Comment (xtuc) [inline src/index.ts:214]: i don't think you need to set the text, it will be probably generated later

Comment (harrishancock) [reply src/index.ts:214]: The answer is yes and no. According to the Fetch spec (at least at the time that we implemented it), the default status text is "OK" for all response status codes. We thought that was a bad default, so we deviated from the spec and codified a set of defaults based on http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml.

So, I think it's good practice to set the statusText for portable code that might also need to run in a browser, but for code that will only run on Cloudflare Workers, it can be safely omitted.

In this particular case, though, I think it's smart to preserve whatever our cache set.

**Review by harrishancock — APPROVED** [review]
My one substantive comment would be that a test would be nice. That might be a bit of a headache, though, from looking at our testing code...

File: src/index.ts (hunk 1 above)
Comment (xtuc) [reply src/index.ts:214]: Good point, yes.

File: src/index.ts [hunk 2]
```diff
@@ -203,7 +203,23 @@ const getAssetFromKV = async (event: FetchEvent, options?: Partial<Options>): Pr
...
+      } else if (headers.has('Content-Range')) {
+        opts.status = 206
+        opts.statusText = 'Partial Content'
```
[the remark this answers is not in the document]
Comment (shagamemnon) [reply src/index.ts:217]: I believe you are correct. In the absence of a test however, removing this code makes me nervous!

And indeed, we are not in a great place testing-wise. That said, I could write a test for this next week to keep things in order

**Review by xtuc — APPROVED** [review]

**Comment by shagamemnon** [comment]
Issue #167 needs to be investigated before proceeding

**Comment by shagamemnon** [comment]
@koeninger this is ready now. Can you squash the commits?

**Comment by koeninger** [comment]
@shagamemnon cool thanks, squashed + merged
