### PR TITLE
Fix browser cache headers from always being set

### LINKED ISSUE #38: Browser Cache issue
Browser cache gets set to edgeTTL on HITS

### PR DESCRIPTION
**Pull request by victoriabernard92**
For cache HITs we always returned the edge cache TTLs to the client, which in turn means the browser would be caching as long as the edge does (100 days)

```
curl -X 'GET' -v https://sites.workers-tooling.cf/workers/ 2>&1 | grep cache
< cf-cache-status: HIT
< cache-control: public, max-age=8640000
```

Also, I set the edge cache to a safer, more realistic value (no edge would likely not get close to caching an asset for 100 days)

fixes #38

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -26,8 +26,8 @@ const mapRequestToAsset = request => {
 }
 
 const defaultCacheControl = {
-  browserTTL: 0,
-  edgeTTL: 100 * 60 * 60 * 24, // 100 days
+  browserTTL: null,
+  edgeTTL: 2 * 60 * 60 * 24, // 2 days
```
Comment (EverlastingBugstopper) [inline src/index.js]: lets keep this at 100?

File: src/index.js [hunk 2]
```diff
@@ -121,6 +121,11 @@ const getAssetFromKV = async (event, options) => {
   if (response) {
     let headers = new Headers(response.headers)
     headers.set('CF-Cache-Status', 'HIT')
+    if(options.browserTTL === null ){
```
Comment (signalnerve) [inline src/index.js]: looks like this needs to go through prettier

Comment (victoriabernard92) [reply src/index.js]: sorry i changed my vscode config been driving me nuts!

File: src/index.js (hunk 1 above)
Comment (victoriabernard92) [reply src/index.js]: it's weird IMO because it would never stay on cache for that long and puts us and developers at risks for situations like this.

**Comment by victoriabernard92** [comment]
> `cache-control: max-age=undefined`
> 
> Hey so this doesn't quite work, I'm fiddling around with it
> 
> I think if you change the `if (options.browserTTL === null)` to if `if (!options.browserTTL)` it seems to work as expected :) should add some tests for this. I am a little confused as to why exactly `options.browserTTL` was undefined in the first place... since you explicitly set it to null

Fixed

File: src/index.js [hunk 3]
```diff
@@ -121,6 +121,13 @@ const getAssetFromKV = async (event, options) => {
   if (response) {
     let headers = new Headers(response.headers)
     headers.set('CF-Cache-Status', 'HIT')
+    if (options.cacheControl.browserTTL === 0 || options.cacheControl.browserTTL) {
```
Comment (EverlastingBugstopper) [inline src/index.js]: I think we should separate this boolean check to its own function that returns a boolean, and it should also return false if `options.cacheControl.browserTTL` is negative

Comment (victoriabernard92) [reply src/index.js]: so like:
```
const toSetBrowserTTL = cacheControl => cacheControl.browserTTL === 0 || cacheControl.browserTTL
```

Comment (EverlastingBugstopper) [reply src/index.js]: readability and also so we don't repeat ourselves, this code is used twice - generally that should be a separate function imo. 

```js
const isValidBrowserTTL = browserTTL => {
  let ttl = parseInt(browserTTL, 10)
  if (typeof ttl !== "number" || ttl < 0) {
    return false
  }
  return true
}
```
