### PR TITLE
Fix tests for custom namespace

### LINKED ISSUE #67: passing a custom namespace binding will not work
at the moment in the code we provide an option to set a custom ASSET_NAMESPACE binding, but it appears that we actually never use it.

If we want this option to work, we need to test and verify the following scenarios:

1. Proof of the bug: Define a kv namespace for both CUSTOM_NAMESPACE and __STATIC_CONTENT. Pass CUSTOM_NAMESPACE in to the function as options.ASSET_NAMESPACE. You would expect to get back the result from CUSTOM_NAMESPACE, but you will actually get back the result from __STATIC_CONTENT.

My working hypothesis is that if the global __STATIC_CONTENT is undefined, this will actually throw an undefined exception in the current code.

2. I fail to bind anything to the global variable CUSTOM_NAMESPACE, and pass it in as part of the options object under ASSET_NAMESPACE. The kv asset handler should throw an InternalError when it does the typeof check against ASSET_NAMESPACE. I believe this happens with the code right now.

3. (Control test): I bind a kv namespace to the global __STATIC_CONTENT and do not pass anything in to the options object. The kv asset handler should call .get on the static content object and return the result.

4. Proof the bug is squashed: run test #1 above. You should get back the response from the CUSTOM_NAMESPACE.

### PR DESCRIPTION
**Pull request by victoriabernard92**
accidentally merged some of these changes in [error handling PR](https://github.com/cloudflare/kv-asset-handler/pull/64) when I saw comments relevant to this PR on that other branch... and that's my bad 😬
Changes already merged in were to fix the tests:
* Add tests for custom namespace  https://github.com/cloudflare/kv-asset-handler/pull/64/commits/151825a29f1e352d6820deaee245e74a7b27cfa0
* Have mocks pass in store https://github.com/cloudflare/kv-asset-handler/pull/64/commits/27f9ae54ba5faafa645fe9400976810349e4c693

This PR just fixes some loss ends with the tests and implementation

fixes #67

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -91,7 +91,7 @@ const getAssetFromKV = async (event: FetchEvent, options?: Partial<Options>): Pr
   }
 
   if (typeof ASSET_NAMESPACE === 'undefined') {
-    throw new InternalError(`there is no KV namespace bound to the script.`)
+    throw new InternalError(`there is no ASSET_NAMESPACE namespace bound to the script`)
```
Comment (victoriabernard92) [inline src/index.ts]:
```suggestion
    throw new InternalError(`there is no KV namespace bound to the script`)
```

File: src/test/getAssetFromKV.ts [hunk 2]
```diff
@@ -217,11 +217,23 @@ test('getAssetFromKV passing in a custom NAMESPACE serves correct asset', async
...
+  const event = getEvent(new Request('https://blah.com'))
+  const error: KVError = await t.throwsAsync(
+    getAssetFromKV(event, { ASSET_NAMESPACE: CUSTOM_NAMESPACE }),
+  )
   t.is(error.status, 404)
 })
+test('getAssetFromKV when namespace not bound fails', async t => {
+  mockGlobal()
+  var MY_CUSTOM_NAMESPACE = undefined
+  Object.assign(global, { MY_CUSTOM_NAMESPACE: undefined })
```
Comment (ashleymichal) [inline src/test/getAssetFromKV.ts]:
```suggestion
  Object.assign(global, { MY_CUSTOM_NAMESPACE })
```

File: src/test/getAssetFromKV.ts [hunk 3]
```diff
@@ -217,11 +217,23 @@ test('getAssetFromKV passing in a custom NAMESPACE serves correct asset', async
...
+
+  const event = getEvent(new Request('https://blah.com/'))
+  const error: KVError = await t.throwsAsync(
+    getAssetFromKV(event, { ASSET_NAMESPACE: MY_CUSTOM_NAMESPACE }),
+  )
+  t.is(error.status, 500)
```
Comment (ashleymichal) [inline src/test/getAssetFromKV.ts]: can this check for the error type?
